---
# Source: dify/templates/proxy-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    
    descriptions: nginx proxy
  labels:
    helm.sh/chart: dify-0.15.0
    app.kubernetes.io/name: dify
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.3.1"
    app.kubernetes.io/managed-by: Helm
    component: proxy
    # app: release-name-dify-proxy
    
  name: release-name-dify-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dify
      app.kubernetes.io/instance: release-name
      component: proxy
      
  template:
    metadata:
      annotations:
        
      labels:
        app.kubernetes.io/name: dify
        app.kubernetes.io/instance: release-name
        component: proxy
        
        
    spec:
      containers:
      - image: "nginx:latest"
        imagePullPolicy: "IfNotPresent"
        name: nginx
        env:
        ports:
          - name: dify
            containerPort: 80
            protocol: TCP
        resources:
            {}
        volumeMounts:
        - name: nginx
          mountPath: /etc/nginx/nginx.conf
          readOnly: true
          subPath: nginx.conf
        - name: nginx
          mountPath: /etc/nginx/proxy.conf
          readOnly: true
          subPath: proxy.conf
        - name: nginx
          mountPath: /etc/nginx/conf.d/default.conf
          readOnly: true
          subPath: default.conf
      volumes:
      - name: nginx
        configMap:
          defaultMode: 420
          name: release-name-dify-proxy
