---
# Source: dify/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-dify
  labels:
    helm.sh/chart: dify-0.15.0
    app.kubernetes.io/name: dify
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.3.1"
    app.kubernetes.io/managed-by: Helm
    component: "proxy"
spec:
  type: ClusterIP
  ports:
    - name: dify
      port: 80
      protocol: TCP
      targetPort: dify
  selector:
    app.kubernetes.io/name: dify
    app.kubernetes.io/instance: release-name
    component: "proxy"
