---
# Source: dify/templates/web-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    
    descriptions: web server
  labels:
    helm.sh/chart: dify-0.15.0
    app.kubernetes.io/name: dify
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.3.1"
    app.kubernetes.io/managed-by: Helm
    component: web
    # app: release-name-dify-web
    
  name: release-name-dify-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dify
      app.kubernetes.io/instance: release-name
      component: web
      
  template:
    metadata:
      annotations:
        
      labels:
        app.kubernetes.io/name: dify
        app.kubernetes.io/instance: release-name
        component: web
        
        
    spec:
      containers:
      - image: "langgenius/dify-web:0.3.1"
        imagePullPolicy: "IfNotPresent"
        name: web
        env:
        - name: EDITION
          value: SELF_HOSTED
        - name: CONSOLE_URL
          value: http://llmops.azurewebsites.net
        - name: APP_URL
          value: http://appllmops.azurewebsites.net
        ports:
          - name: web
            containerPort: 3000
            protocol: TCP
        resources:
            {}
