---
# Source: dify/charts/postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: release-name-postgresql
  namespace: "default"
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-12.5.6
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  postgres-password: "ZGlmeWFpMTIzNDU2"
  replication-password: "MURwSkZyaTgxQw=="
  # We don't auto-generate LDAP password when it's not provided as we do for other passwords
