---
# Source: dify/templates/api-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    
    descriptions: api
  labels:
    helm.sh/chart: dify-0.15.0
    app.kubernetes.io/name: dify
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.3.1"
    app.kubernetes.io/managed-by: Helm
    component: api
    # app: release-name-dify-api
    
  name: release-name-dify-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dify
      app.kubernetes.io/instance: release-name
      component: api
      
  template:
    metadata:
      annotations:
        
      labels:
        app.kubernetes.io/name: dify
        app.kubernetes.io/instance: release-name
        component: api
        
        
    spec:
      containers:
      - image: "langgenius/dify-api:0.3.1"
        imagePullPolicy: "IfNotPresent"
        name: api
        env:
        - name: CHECK_UPDATE_URL
          value: ""
        envFrom:
          - configMapRef:
              name: release-name-dify-api
        ports:
          - name: api
            containerPort: 5001
            protocol: TCP
        resources:
            {}
        volumeMounts:
        - name: app-data
          mountPath: "/app/api/storage"
          subPath: 
      volumes:
      - name: app-data
        persistentVolumeClaim:
          claimName: release-name-dify
