---
# Source: dify/templates/api-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-dify-api
data:
  # Startup mode, 'api' starts the API server.
  MODE: api
  # The log level for the application. Supported values are `DEBUG`, `INFO`, `WARNING`, `ERROR`, `CRITICAL`
  LOG_LEVEL: INFO
  # A secret key that is used for securely signing the session cookie and encrypting sensitive information on the database. You can generate a strong key using `openssl rand -base64 42`.
  SECRET_KEY: sk-9f73s3ljTXVcMT3Blb3ljTqtsKiGHXVcMT3BlbkFJLK7U
  # The base URL of console application, refers to the Console base URL of WEB service if console domain is
  # different from api or web app domain.
  # example: http://cloud.dify.ai
  CONSOLE_URL: http://llmops.azurewebsites.net
  # The URL for Service API endpoints，refers to the base URL of the current API service if api domain is
  # different from console domain.
  # example: http://api.dify.ai
  API_URL: http://apillmops.azurewebsites.net
  # The URL for Web APP, refers to the Web App base URL of WEB service if web app domain is different from
  # console or api domain.
  # example: http://udify.app
  APP_URL: http://appllmops.azurewebsites.net
  # When enabled, migrations will be executed prior to application startup and the application will start after the migrations have completed.
  MIGRATION_ENABLED: "true"
  
  # The configurations of postgres database connection.
  # It is consistent with the configuration in the 'db' service below.
    
  DB_USERNAME: postgres
  DB_PASSWORD: difyai123456
  DB_HOST: release-name-postgresql-primary
  DB_PORT: "5432"
  DB_DATABASE: dify
  
  # The configurations of redis connection.
  # It is consistent with the configuration in the 'redis' service below.
  REDIS_HOST: release-name-redis-master
  REDIS_PORT: "6379"
  REDIS_USERNAME: ""
  REDIS_PASSWORD: "difyai123456"
  REDIS_USE_SSL: "false"
  # use redis db 0 for redis cache
  REDIS_DB: "0"
  
  # The configurations of session, Supported values are `sqlalchemy`. `redis`
  SESSION_TYPE: redis
  SESSION_REDIS_HOST: release-name-redis-master
  SESSION_REDIS_PORT: "6379"
  SESSION_REDIS_USERNAME: ""
  SESSION_REDIS_PASSWORD: "difyai123456"
  SESSION_REDIS_USE_SSL: "false"
  # use redis db 2 for session store
  SESSION_REDIS_DB: "2"
  # The configurations of celery broker.# Use redis as the broker, and redis db 1 for celery broker.
  CELERY_BROKER_URL: redis://:difyai123456@release-name-redis-master:6379/1
  # Specifies the allowed origins for cross-origin requests to the Web API, e.g. https://dify.app or * for all origins.
  WEB_API_CORS_ALLOW_ORIGINS: '*'
  # Specifies the allowed origins for cross-origin requests to the console API, e.g. https://cloud.dify.ai or * for all origins.
  CONSOLE_CORS_ALLOW_ORIGINS: '*'
  # CSRF Cookie settings
  # Controls whether a cookie is sent with cross-site requests,
  # providing some protection against cross-site request forgery attacks
  #
  # Default: `SameSite=Lax, Secure=false, HttpOnly=true`
  # This default configuration supports same-origin requests using either HTTP or HTTPS,
  # but does not support cross-origin requests. It is suitable for local debugging purposes.
  #
  # If you want to enable cross-origin support,
  # you must use the HTTPS protocol and set the configuration to `SameSite=None, Secure=true, HttpOnly=true`.
  #
  # For **production** purposes, please set `SameSite=Lax, Secure=true, HttpOnly=true`.
  COOKIE_HTTPONLY: 'true'
  COOKIE_SAMESITE: 'Lax'
  COOKIE_SECURE: 'false'
  # The type of storage to use for storing user files. Supported values are `local` and `s3`, Default: `local`
  STORAGE_TYPE: local
  # The path to the local storage directory, the directory relative the root path of API service codes or absolute path. Default: `storage` or `/home/john/storage`.
  # only available when STORAGE_TYPE is `local`.
  STORAGE_LOCAL_PATH: /app/api/storage
  # The type of vector store to use. Supported values are `weaviate`, `qdrant`.
  VECTOR_STORE: weaviate
  # The Weaviate endpoint URL. Only available when VECTOR_STORE is `weaviate`.
  
  WEAVIATE_ENDPOINT: "http://weaviate"
  # The Weaviate API key.
  WEAVIATE_API_KEY: WVF5YThaHlkYwhGUSmCRgsX3tD5ngdN8pkih
  # The DSN for Sentry error reporting. If not set, Sentry error reporting will be disabled.
  SENTRY_DSN: ''
  # The sample rate for Sentry events. Default: `1.0`
  SENTRY_TRACES_SAMPLE_RATE: "1.0"
  # The sample rate for Sentry profiles. Default: `1.0`
  SENTRY_PROFILES_SAMPLE_RATE: "1.0"
