---
# Source: dify/templates/proxy-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-dify-proxy
data:
  proxy.conf: |-    
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_buffering off;
    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;
  nginx.conf: |-    
    user  nginx;
    worker_processes  auto;
    pid        /var/run/nginx.pid;
    
    
    events {
        worker_connections  1024;
    }
    
    
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
    
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
    
        sendfile        on;
        #tcp_nopush     on;
    
        keepalive_timeout  65;
    
        #gzip  on;
        client_max_body_size 15M;
    
        include /etc/nginx/conf.d/*.conf;
    }
  default.conf: |-    
    server {
        listen 80;
        server_name _;
    
        location /console/api {
          proxy_pass http://release-name-dify-api:5001;
          include proxy.conf;
        }
    
        location /api {
          proxy_pass http://release-name-dify-api:5001;
          include proxy.conf;
        }
    
        location /v1 {
          proxy_pass http://release-name-dify-api:5001;
          include proxy.conf;
        }
    
        location / {
          proxy_pass http://release-name-dify-web:3000;
          include proxy.conf;
        }
    }
