---
# Source: dify/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: release-name-dify
  annotations:
    helm.sh/resource-policy: keep
  labels:
    helm.sh/chart: dify-0.15.0
    app.kubernetes.io/name: dify
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.3.1"
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes:
  - "ReadWriteMany"
  resources:
    requests:
      storage: 5Gi
